### ISSUE TITLE
WildernessTP doing something that is wack - BlurredBlockBreakEvent 

### ISSUE THREAD

**Issue by skw359** [AcmeProject/WildernessTp#109]
I'm getting these console errors, I think due to Wilderness TP. Here's the log: https://pastebin.com/xZLFwKyU
I think Wildernesstp is doing something which is triggering ecoenchant to ask if the player is allowed to do something, which is triggering towny's playercache, thus the error. The error is also saying that the player has no valid locale (but that can't happen to a regular player). 
From the logs, I see
```
         at net.poweredbyhate.wildtp.WildWarrantTax.n0tAGreifClam(WildWarrantTax.java:136) ~[WildTP.jar:?]
        at net.poweredbyhate.wildtp.WildWarrantTax.chekar(WildWarrantTax.java:108) ~[WildTP.jar:?]
        at net.poweredbyhate.wildtp.WildWarrantTax.lambda$search$0(WildWarrantTax.java:69) ~[WildTP.jar:?]
```
which is the earliest the error mentions anything relevant about a plugin

From what I can see too, the failing variable is `iHopePluginsDontFreakOutOverThis` because of this code:
```
    private boolean n0tAGreifClam(Location l0c0) {
        if ((useExperimentalChekar || useOtherChekar) && player != null) {
            try {
                BlurredBlockBreakEvent iHopePluginsDontFreakOutOverThis
                        = new BlurredBlockBreakEvent(l0c0.getBlock(), new JohnBonifield(player));
```

Let me know if there's anything else I might be missing or can include :)

*This error occurs when a player does `/rtp` (and from what I can see, lands in a town from that wild teleport)

**Comment by RoboMWM** [comment]
Need more than that. All stacktraces and errors please.

**Comment by RoboMWM** [comment]
hmm, not sure if I missed the pastebin log, o well.

**Comment by RoboMWM** [comment]
but yea, probably would need to set locale in the dummy player object that's generated
