### ISSUE TITLE
Player being teleport in block they should be standing on

### ISSUE THREAD

**Issue by Gnoarn** [AcmeProject/WildernessTp#24]
Player appears to be stuck in block they are standing on. ran this several times to check the results.
1.13 R2
default settings for this plugin
limited plugins 
multiverse
luckperms
worldborder
protocolsupport

**Comment by RoboMWM** [comment]
full output of `/version` ? Need to know if you're running paper, spigot, CB, etc.

Also, output of `/version wild`

**Comment by Gnoarn** [comment]
git-Spigot-2440e18-4228a56 1.13.1-R01
Wild 2.1

**Comment by RoboMWM** [comment]
Ok thanks. Highly recommend upgrading to paper btw. Will test with spigot now... btw, is this in any particular biome or world environment? Because the nether check for example is different.

**Comment by RoboMWM** [comment]
Oof spigot is soooo slow with sync chunk gens and loads. Anyways, this is weird, it seems to only be happening for me with newly generated chunks, or at least with only grass blocks...? Perhaps it has something to do with the client not loading the chunk fast enough, thus thinking they're a block lower than they're supposed to be?

WildernessTP is definitely teleporting them above the block, so gonna guess this is something to do with the client, or with spigot. ![](https://i.imgur.com/Z9VTYDn.png)

**Comment by RoboMWM** [comment]
Yea, that seems to be the issue. One of my tests teleported me to a tiny pond within a plains biome, with a one block depth with a dirt floor. WildTP properly found the water block and attempted to teleport me just above that. However, when the chunk finally loaded for me, I was stuck in the dirt block!

I'll see what I can do to mitigate, but I've had 0 complaints nor experienced this issue on my Paper server, where chunk loads and generations are asynchronous, allowing the server to deliver the chunks to the player sooner and faster (whereas spigot interleaves chunk sending with other server tasks).

**Comment by Gnoarn** [comment]
have been debating about porting to paper. was just having issues with backwards client compatability at least with using epic world generator. had a couple ports to deep water today but the map is not been fully generated yet. thank you.

**Comment by RoboMWM** [comment]
Hmm, idk what stuff EpicWorldGenerator does that wouldn't make it have issues with Paper. I do know the developer has done stuff like put in a remote switch he could activate to encrypt all of your files if he suspected you were pirating the plugin, so I don't expect too much in terms of code quality.

Anyways, would discuss with Paper on their IRC/discord and/or with the developer regarding Paper issues, Paper will resolve any issues if it is on their side.
