### ISSUE TITLE
per world sizes/world border plugin support

### ISSUE THREAD

**Issue by FrozenBeard** [AcmeProject/WildernessTp#26]
my main world is much bigger than my end/nether, so when its used in the end, it just puts them into the void as 99% of the time it trys to put them outside the world border, so teleporst them to the middle, which is under the main island, killing them.
Need to be able to set a world size per world.

**Comment by RoboMWM** [comment]
Will now respect vanilla world border if configured values are larger than it.

**Comment by FrozenBeard** [comment]
An nuts, I use https://www.spigotmc.org/resources/worldborder.60905/ support this please

**Comment by RoboMWM** [comment]
I'll add support I guess - in the meantime you can set the vanilla /worldborder to match it (`/minecraft:worldborder`)

**Comment by RoboMWM** [comment]
In 2.5 which is pending release
