### ISSUE TITLE
permission to use sign

### ISSUE THREAD

**Issue by FrozenBeard** [AcmeProject/WildernessTp#27]
request to create permission to use teleport signs.

**Comment by RoboMWM** [comment]
Can you tell me why you'd want to do this? I'd imagine it's possible to just disable interactions in whatever area you don't want some players to use a random tp sign...?

**Comment by FrozenBeard** [comment]
Simple, I just want /wild for new people (first rank), but having signs is handy for them to know it exists, so checking they have permission to use it would be the best solution, then if I change my mind I can just move the permission.

**Comment by RoboMWM** [comment]
`wild.wildtp.sign` in upcoming update

**Comment by FrozenBeard** [comment]
Thanks
