### ISSUE TITLE
Could not pass event BlurredBlockBreakEvent to EnchantsPlus

### ISSUE THREAD

**Issue by SmallSansSerif** [AcmeProject/WildernessTp#28]
Could not pass event BlurredBlockBreakEvent to EnchantsPlus. 

https://pastebin.com/Bcx8su2y

Any way you can look at this error and possible fix? 

https://www.spigotmc.org/resources/enchantsplus.3396/

**Comment by RoboMWM** [comment]
No I can't until I'm told what line 259 in ListenerApplyEnchantEffects.java is.

In the meantime you can try the alternative global claim check.

**Comment by SmallSansSerif** [comment]
I can't get a hold of this author unfortunately. It's a well-used paid Spigot plugin too which is too bad.

Any other ideas? Still got error on alternative global claim check.

**Comment by RoboMWM** [comment]
On the alternative one? You disabled the other one correct?

Anyways thanks for the code snippet, that helps a lot, will push out an update soon.

> It's a well-used paid Spigot plugin too which is too bad.

Yea, there generally almost always are better alternatives that are open source. Being a "premium" plugin is hardly an excuse to not be open source...

**Comment by SmallSansSerif** [comment]
I received that error on both modes if that makes sense. Thanks will try the update.

**Comment by SmallSansSerif** [comment]
So basically ignore the error in log? You can't suppress it with your plugin is what you are saying?

**Comment by RoboMWM** [comment]
Yes.

I'm not even sure why it's executing code since it's supposed to ignore if canceled.

But yes, ignore stacktrace. Still working on other things for update.
