### ISSUE TITLE
Update for latest WorldGuard/WorldEdit Vector System needed plz

### ISSUE THREAD

**Issue by axemwa** [AcmeProject/WildernessTp#29]
[20:31:09 ERROR]: [Wild] Plugin Wild v2.3 has failed to register events for class net.poweredbyhate.wildtp.PortalzGoneWild because com/sk89q/worldedit/Vector does not exist.

**Comment by RoboMWM** [comment]
So WorldEdit performed stupid again and somehow put an older snapshot version with a larger build number in their maven repo, causing the plugin to download the older variant of WorldEdit as the "latest snapshot."

Honestly don't even know what's going on with me4502.

**Comment by RoboMWM** [comment]
WorldEdit's current situation is stupid.

**Comment by RoboMWM** [comment]
I already updated it, update is approved on bukkit, will post on spigot when I get home.
