### ISSUE TITLE
Water avoidance

### ISSUE THREAD

**Issue by LogGits** [AcmeProject/WildernessTp#30]
Hey, I made a post on the discussion page about water avoidance. Would you be able to add this in. I want to convert to this plugin. However, players do get afk pushed into wild portals and therefore, it isn't a safe location for a player to be teleported to. The plugin looks great, keep up the great work 👍

**Comment by RoboMWM** [comment]
Blocking the relevant ocean biomes aren't enough? (You can let them regen by deleting them all in your config.)

**Comment by LogGits** [comment]
Initially i thought so, but in my testing. Biomes bleed in to other biomes. E.g. This is a plains biome and its clearly underwater:
https://gyazo.com/b05c9a2ae0485cbb6a3a212d6805924d

An afk player who gets teleported here will die

**Comment by RoboMWM** [comment]
alrighty, thanks.

**Comment by RoboMWM** [comment]
IMO if afk pushing is really an issue you probably shouldn't have portals. ¯\_(ツ)_/¯

**Comment by RoboMWM** [comment]
You can add WATER to BlockedBlocks
