### ISSUE TITLE
use in world spawns player below ground level

### ISSUE THREAD

**Issue by mrcoffee1026** [AcmeProject/WildernessTp#35]
just slightly below ground level like what happens when you tp a player onto a grass path block or onto a snow layer block... except on every use of /wild in the main world only - for some reason.  I don't have this issue when trying /wild in the nether or in the end.  Player is stuck to ground until they /unstuck with w/e command or find some magical way of glitching out of the block.  I tried the config option dropPlayerFromAbove: true and this somewhat solves the issue but shouldn't be necessary to use this in the main world, i'm not sure why it would be miscalculating y at all.

**Comment by RoboMWM** [comment]
Duplicate of #24 

TL;DR: y value is not being miscalculated, switch to Paper or the option you're already using.

**Comment by RoboMWM** [comment]
Duplicate of #24
