### ISSUE TITLE
Buggy Portals

### ISSUE THREAD

**Issue by freakyy85** [AcmeProject/WildernessTp#36]
Hi! Well, I created a portal, I 1. can't delete it, just does nothing (the command) 2. theres nothing displayed at the portal - means, just walking through air teleports you but, theres no "gate" effect or whatsoever. It would be nice if you could fix this.

Oh and, sign permissions dont seem to work aswell. OP can teleport, normal users cant. even with permissions (Vault). they can use /wild though :)

**Comment by RoboMWM** [comment]
Owners use their own effects. Usually a waterfall or similar.

Deletion should work fine, check portals.yml
