### ISSUE TITLE
permission node to bypass cooldown?

### ISSUE THREAD

**Issue by mrcoffee1026** [AcmeProject/WildernessTp#37]
Is there (or could there be added) a permission node to bypass cooldown (for higher ranked players)?

**Comment by RoboMWM** [comment]
There is a permission node.

**Comment by RoboMWM** [comment]
Hmm, not documented. Not sure if it was permission or command-based

**Comment by mrcoffee1026** [comment]
Great would you mind adding it to the site or letting me know what it is as all the perms are listed here don't show what it is:

Permissions:
wild.wildtp - Give player access to /wild
wild.wildtp.world - Give player access to /wild [world]
wild.wildtp.direction - Give player access to /wild [north/south/east/west]
wild.wildtp.others - Gives the player the ability to use /wild on other players
wild.wildtp.reload - Gives the player the ability to reload the plugin's config
wild.wildtp.create.sign - Gives the player ability to create WildTp signs
wild.wildtp.break.sign - Allows the player to break wildtp signs
wild.wildtp.sign - Allows the player to use WildTP signs
wild.wildtp.set - opens the gui
wild.wildtp.create.portal - Allows creation, listing, and deletion of portals

**Comment by mrcoffee1026** [comment]
I took a "wild" stab at it, this seems to be it: - wild.wildtp.cooldown.bypass

**Comment by RoboMWM** [comment]
Nice lol. Yea, don't know why the bypass perms aren't listed. wild.wildtp.delay.bypass for warmup

**Comment by mrcoffee1026** [comment]
oh that's a sweet one to have to i suppose.  I just dropped it to like 3 seconds I figure that might be enough  to keep people from spamming the command although it doesn't seem as big of an issue with this plugin as it has been with others i've tried.  This is very clean even with the ridiculous range I put in it.  Thanks much!

**Comment by RoboMWM** [comment]
> although it doesn't seem as big of an issue with this plugin as it has been with others i've tried.

Yup, if you're on Paper, it's because it's using the async chunk load API.
