### ISSUE TITLE
can't tp players from console using + on join tp

### ISSUE THREAD

**Issue by quiquelhappy** [AcmeProject/WildernessTp#39]
I can't tp players from console using /player <name> world. Please, add this, or fix the on-first-join thing, I've it enabled but it isn't working at all. Thank you very much <3

**Comment by RoboMWM** [comment]
Do the players have permission to run /wild on first join? Also paste `version wild`

**Comment by quiquelhappy** [comment]
Version 3.15.2.
Yes, they do have permission

**Comment by RoboMWM** [comment]
You're using the wrong plugin. Please download from here https://www.spigotmc.org/resources/22853/
