### ISSUE TITLE
NO_MONEY message not showing when player has insufficient funds

### ISSUE THREAD

**Issue by arboriginal** [AcmeProject/WildernessTp#46]
From [Lammendam](https://www.spigotmc.org/members/lammendam.299617/) on [Spigot forum](https://www.spigotmc.org/threads/wilderness-tp.145440/page-25#post-3579773)

> fix NO_MONEY message because this string isn't showing when player has insufficient funds

**Patch to fix it:**
[patch.diff.zip](https://github.com/AcmeProject/WildernessTp/files/3725989/patch.diff.zip)

**Comment by arboriginal** [comment]
As Lammerdam as explained the second part of his bug report...

**Updated patch:**
[patch.diff.zip](https://github.com/AcmeProject/WildernessTp/files/3726083/patch.diff.zip)

**Comment by RoboMWM** [comment]
Not sure what you're uploading patches for, is it to remind yourself later or something?

**Comment by arboriginal** [comment]
Nope, patches are for you: you apply them and you have the problem solved.
Faster than create a fork & PR only to change a few lines of code.

**Comment by RoboMWM** [comment]
> Faster than create a fork & PR only to change a few lines of code.

I beg to differ.

Any reason why you're no longer making changes on a fork? It's way faster and if you're tracking upstream then you just create new branches from the upstream branch so you don't have to worry about merge conflicts when pulling upstream on a single branch.

**Comment by RoboMWM** [comment]
```
error: patch failed: src/main/java/net/poweredbyhate/wildtp/TeleportGoneWild.java:61
error: src/main/java/net/poweredbyhate/wildtp/TeleportGoneWild.java: patch does not apply
```

Not easier IMO along with manual download but either way thanks.

**Comment by RoboMWM** [comment]
Ok so `git am --signoff "/d/Downloads/patch.diff"` results in `Patch format detection failed.` but it's able to do other things so idk what's going on.

```bash
$ git am --signoff < "/d/Downloads/patch.diff"
.git/rebase-apply/patch:18: trailing whitespace.

.git/rebase-apply/patch:24: trailing whitespace.

warning: 2 lines add whitespace errors.
fatal: empty ident name (for <>) not allowed
Applying:
```

Ok I looked in the file and I don't see any authorship info so that's probably why it can't just be applied. (i.e. I'm guessing this is some bare bones diff and not a full patch I can just apply)
