### ISSUE TITLE
/wild on world_the_end teleporting into the void.

### ISSUE THREAD

**Issue by SrBedrock** [AcmeProject/WildernessTp#47]
Hi guys!

Almost every time the `/wild` command is used on the end or `/wild world_the_end` the player dies on void. In previous version 2.10 I did not have this problem.

[My WildTP config.yml on hastebin.in](https://hasteb.in/suwulize.yaml)

I put the air block to see if it resolved and nothing changed.

```yml
BlockedBlocks:
- AIR
- CACTUS
- FIRE
- LAVA
- MAGMA_BLOCK
```

Information when using `/wild` and being teleported to the void:
```log
>.... [00:42:50 INFO]: ThiagoROX issued server command: /wild
>.... [00:42:50 INFO]: [WildTP] Wild command called by CraftPlayer{name=ThiagoROX}
>.... [00:42:50 INFO]: [WildTP] Wild teleport called for ThiagoROX for world world_the_end
>.... [00:42:50 INFO]: [WildTP] ThiagoROX called /wild args 0
>.... [00:42:52 INFO]: ThiagoROX issued server command: /wild $hut Up And Take My M0ney!
>.... [00:42:52 INFO]: [WildTP] Wild command called by CraftPlayer{name=ThiagoROX}
>.... [00:42:52 INFO]: [WildTP] Cooldown check requested for 3098723f-0cac-3b7c-9a14-ef6aaec9c26f
>.... [00:42:52 INFO]: [WildTP] Player has bypass perms
>.... [00:42:52 INFO]: [WildTP] Calling preTeleportEvent
>.... [00:42:52 INFO]: [WildTP] Called preWildTeleportEvent
>.... [00:42:52 INFO]: [WildTP] preping 2 port 2 Location{world=CraftWorld{name=world_the_end},x=57.0,y=0.0,z=-7509.0,pitch=0.0,yaw=0.0}
>.... [00:42:52 INFO]: [WildTP] Teleporting ThiagoROXLocation{world=CraftWorld{name=world_the_end},x=57.0,y=0.0,z=-7509.0,pitch=0.0,yaw=0.0}
>.... [00:42:52 INFO]: [WildTP] ThiagoROX Teleported to Location{world=CraftWorld{name=world_the_end},x=57.5,y=0.5,z=-7508.5,pitch=0.0,yaw=-119.10001}
>.... [00:42:52 INFO]: Changed title display times for ThiagoROX
>.... [00:42:52 INFO]: Showing new subtitle for ThiagoROX
>.... [00:42:52 INFO]: Showing new title for ThiagoROX
```

WildTP Version: **2.12**
Server Version: **Paper-214**

**Comment by RoboMWM** [comment]
Ya, arboriginal's PR somehow ignores the "badBlocks" check when I'm opped so there's some permission that ignores this check. It doesn't tp me to the void otherwise. If you can figure out which permission it is that'd help a lot.

**Comment by SrBedrock** [comment]
I used the LuckPerms verbose tool.

![image](https://user-images.githubusercontent.com/51332006/67739904-c724f280-f9f2-11e9-9ae9-540c7a8187df.png)

[LuckPerms Verbose Link](https://luckperms.net/verbose/#j3w1qOZbLZ)

**Comment by RoboMWM** [comment]
Ok, so the last PR I pulled removed the air blocks check, so I'll put those in the default config. (There are now 3 air blocks in 1.14, so you need to add VOID_AIR and CAVE_AIR too).

**Comment by SrBedrock** [comment]
hmm Thanks!! s2

**Comment by SrBedrock** [comment]
After adding the new blocks my problem has been solved! Thank you very much @RoboMWM

**Comment by RoboMWM** [comment]
Thank you for confirming. This default will be added in the next release. Not sure about existing configs though, hmmm...

**Comment by RoboMWM** [comment]
Was thinking of doing some complicated config versioning thing to retroactively add this but decided against that largely-unneeded complexity.
