### ISSUE TITLE
Error on sign click

### ISSUE THREAD

**Issue by Gracv** [AcmeProject/WildernessTp#59]
If a player click a sign this error show up:
https://pastebin.com/U769NSzi

Config:
https://pastebin.com/UVb8METE

Paper 1.13.2

**Comment by RoboMWM** [comment]
Gonna guess you have a wildtp sign somewhere with an invalid world in it.

**Comment by Gracv** [comment]
> 
> 
> Gonna guess you have a wildtp sign somewhere with an invalid world in it.

Error shows up even when I put world name on line 3. Blank = error, world name = error. And yes, name of the world is correct.

**Comment by R4z0rX** [comment]
Same here for Spigot 1.14.4, with default config and same tests (sign with [wildtp] in 1st line only, and with world in 3rd line too)
Error: [https://pastebin.com/DLfDNCgu](https://pastebin.com/DLfDNCgu)

The command /wild works fine.

**Comment by R4z0rX** [comment]
Same with latest build of Paper (#242).
Error: https://pastebin.com/G1ajJEiz

**Comment by dpill83** [comment]
Also have this error.
Error: https://pastebin.com/zZ4ysj7f

**Comment by RoboMWM** [comment]
Fixed, one of the massive PRs I pulled refactored the sign-click logic and broke the debug command, so that's fun.
