### ISSUE TITLE
Random teleport destination Y level

### ISSUE THREAD

**Issue by x1p** [AcmeProject/WildernessTp#61]
All to often, (lets say around 20%) players are teleported to a level way below the sea level.
So I tried the `dropPlayerFromAbove: true` option.
Even then, I got teleported to level 2 with my head stuck in the bedrock.
Once I got teleported beneath bedrock and "fell of the world"

Why can't I enter a minimum Y level to prevent deep trenches and caves?

Paper 1.15.2 build 105

**Comment by RoboMWM** [comment]
Duplicate of #60. This is due to an alleged spigot change.

**Comment by RoboMWM** [comment]
Duplicate of #60

**Comment by RoboMWM** [comment]
Actually, I'm guessing your world is a vanilla nether world?

**Comment by x1p** [comment]
Overworld actually
