### ISSUE TITLE
Console Error - BlockBreakEvent

### ISSUE THREAD

**Issue by LucidAPs** [AcmeProject/WildernessTp#67]
Minecraft: 1.15.2
Tuinity: build 13
Java 11
WildTP : v2.15

https://pastebin.com/raw/vcdQQ1fX

**Comment by RoboMWM** [comment]
did I not release wildtp 2.16?

**Comment by RoboMWM** [comment]
ok I guess not

**Comment by RoboMWM** [comment]
oh it was a different issue tho. This one's a duplicate.

**Comment by RoboMWM** [comment]
Duplicate of #53

**Comment by RoboMWM** [comment]
Fix by restarting server. See comments for more details.
