### ISSUE TITLE
2.15 Is Completely Unusable

### ISSUE THREAD

**Issue by DGJM** [AcmeProject/WildernessTp#68]
The new Version WildernessTP 2.15 has many bugs, 
first off, the adminGUI is broken, it bearly works and,
 wildtp dont work on other Worlds, even adding it in the config, and even if i get it work, it only teleport me to spawn.

took me the whole day, and just fixed it by using an older version(which is 2.14)
edit: using Paper 1.14.4

**Comment by DGJM** [comment]
PLS either FIx the issues or revert back to the old one, the old one is better.

**Comment by RoboMWM** [comment]
There's a 2.16.

Not sure why it's not released.

**Comment by RoboMWM** [comment]
hmm, if it's fixed by reverting, sounds like that PR really did screw a ton of things up

wonder if I should just revert the version and then cherry-pick new features idk

**Comment by RoboMWM** [comment]
anyways, sounds like worldborder stuff may be messed up. I fixed some but should only be in cases where your border is irregular
