### ISSUE TITLE
Wild teleport while flying

### ISSUE THREAD

**Issue by WeelHull** [AcmeProject/WildernessTp#69]
Hi, is there way trough any config be able to do /wild while falling on wilderness plugin I want to enable this please but can't find option inside config.

**Comment by RoboMWM** [comment]
what

You can /wild wherever you are.

Just disable the wait.

**Comment by WeelHull** [comment]
I've tried that still pops up the same message.

You can't use this command while falling.

**Comment by RoboMWM** [comment]
Set wait to 0. It's not going to check movement if the wait is nothing

**Comment by RoboMWM** [comment]
Well, looks like I am wrong, this is a "fix" from the massive PR I pulled that caused a lot of other issues to appear here in this tracker

**Comment by RoboMWM** [comment]
It's one of the bullet points in #44
