### ISSUE TITLE
Not working with paper-165

### ISSUE THREAD

**Issue by niqoar** [AcmeProject/WildernessTp#70]
With the changes applied to paper-165, the plugin sometimes not finds a safe place.

Log: https://pastebin.com/LqXfWE7u

**Comment by RoboMWM** [comment]
Finds not a safe place? Can you elaborate and find any patterns?

**Comment by RoboMWM** [comment]
Hmm, that log is not saying what you are saying. I guess async chunk loading changed, maybe

**Comment by niqoar** [comment]
You just see this: https://i.imgur.com/jVQyl0H.png and throws the error in console without ever teleporting. Back to paper-164 fixes the problem.

**Comment by RoboMWM** [comment]
Hmm, wonder what paper changed then.

**Comment by RoboMWM** [comment]
Yup, seems there are bugs introduced from that. Looks like they've been doing several bug fixes soon after. So, I guess keep updating. Paper issue. https://papermc.io/ci/job/Paper-1.15/changes
