### ISSUE TITLE
Unable to disable world allowed for /wild

### ISSUE THREAD

**Issue by Carbonixx** [AcmeProject/WildernessTp#72]
I've gone through the entire of the config and cannot seem to find a world disable as i don't want it enabled while in the nether, is this possible?

**Comment by RoboMWM** [comment]
Yes, don't grant, or revoke permissions for players in the nether.

**Comment by Carbonixx** [comment]
> Yes, don't grant, or revoke permissions for players in the nether.

How do i do this?

**Comment by RoboMWM** [comment]
via your permissions plugin.
