### ISSUE TITLE
RandomWorld always teleports you to nether if nether is set to 0.

### ISSUE THREAD

**Issue by kakd** [AcmeProject/WildernessTp#73]
I'm not sure if I'm setting this up incorrectly or if the plugin is simply ignoring the values I put into the config. My config: https://hasteb.in/adakowod.yaml.

I wanted to make it so that using /rtp from any world would always make you rtp in the overworld, and to do this, I enabled the randomWorlds option and made world_nether have 0 chance of being teleported into as seen in my config. I reloaded the plugin with /wildtp reload, and used /rtp while in the overworld to test it out. I expected to be teleported to a random point in the overworld, but I was instead teleported to a random point in the nether. Did I configure this wrong? Is it possible for me to make /rtp always teleport into the overworld? If such a feature does not exist, could you please add one? Thanks!

**Comment by RoboMWM** [comment]
Idk if the math was refactored, it may have been. Just set the other world to a large value or remove it altogether...

**Comment by RoboMWM** [comment]
Ok I see, setting it to 0 will make it override the previous entry. So don't do that. If the entry keeps reappearing, well, I'm going to fix that now.

**Comment by RoboMWM** [comment]
actually, I'll just remove it from the list if it's less than 1.
