### ISSUE TITLE
Plugin undetect worlds.

### ISSUE THREAD

**Issue by ImHumbug** [AcmeProject/WildernessTp#74]
Hi, I tried latest version of the plugin (for 1.15.2) on multiple servers. The problem is that when you start the server the plugin is working fine, but suddenly it stops working on worlds that are not the main. For example my main world is called "world" and I have a second one called "resources". When I type /wild resources nothing happends. There is no error in  console, tried with debug mode and it just said that player request the teleport but nothing happends. The strange thing is that always happends suddenly and the quick fix is giving a reload with plugman.

**Comment by RoboMWM** [comment]
is your resources world being reloaded?

**Comment by ImHumbug** [comment]
No, also happens with the end and the nether, when I refer to the reload using plugman I'm making reference to the plugin, not reloading all server.

**Comment by ImHumbug** [comment]
>.... [03:09:10 INFO]: [WildTP] Wild command called by CraftPlayer{name=MatiTheCreator}
>.... [03:09:10 INFO]: [WildTP] MatiTheCreator called /wild <world> (Recursos)
That's the debug but nothing happens.

**Comment by RoboMWM** [comment]
I'm aware you're just reloading the plugin. I don't see why this would "lose" the worlds. My guess is some task is probably interfering.

**Comment by ImHumbug** [comment]
F

**Comment by RoboMWM** [comment]
can you determine what causes this to occur?

**Comment by RoboMWM** [comment]
Also, output of `/version`?

**Comment by RoboMWM** [comment]
anyways it should print help at you if you mess up, but I may have found the issue thanks to someone in IRC chat for once. Wish he made a PR tho. But anyways, when 2.18 is released this should be fixed.

**Comment by RoboMWM** [comment]
Whenever 2.18 gets approved lemme know.
