### ISSUE TITLE
`wait` feature broken in 2.17

### ISSUE THREAD

**Issue by x1p** [AcmeProject/WildernessTp#77]
From 2.17 and beyond, Wild stopped working for me. 2.16 works fine though.
Situation:
From 2.17 executing wild by a player doesn't work. The screen flashes, the message `Teleporting in 5 seconds` appears. But nothing happens.

When they have the permission `wild.wildtp.delay.bypass` they are able to teleport fine although without delay but at least they can teleport.

Permissions:
Normally with version 2.16, `wild.wildtp` should be fine.
Now they can't teleport without having `wild.wildtp.delay.bypass`

**Comment by RoboMWM** [comment]
interesting
I have `wait` set to 0 on my server so I never tested this case.
Ugh.

Anything in console when you enable debug messages?

**Comment by niqoar** [comment]
The same here, 5 seconds and the player does not teleport.

https://pastebin.com/h4C1L3PB

**Comment by RoboMWM** [comment]
interesting, it failed first location but found a second safe location, prepared to teleport, and didn't. So somewhere when I was refactoring I didn't set that the player is all good for teleporting I guess... thought I moved that line in somewhere, guess not.

**Comment by RoboMWM** [comment]
ok no that's right... so something else is stopping it.

**Comment by RoboMWM** [comment]
mk, so the task isn't executing or it's getting canceled somewhere

**Comment by RoboMWM** [comment]
mk, think I found what's going on, 2.19 should have the fix.

**Comment by x1p** [comment]
Build the latest version from github and I can confirm it works.

**Comment by RoboMWM** [comment]
Thanks

I'm wondering if the existing logic that was there was inadvertently incorrect, but still worked because of the order of operations that occurred there.
