### ISSUE TITLE
"wait" value effectively disables plugin for everyone except op players`

### ISSUE THREAD

**Issue by mrcoffee1026** [AcmeProject/WildernessTp#78]
Any value over 0 will cause all tp attempts to fail unless the user has permissions to bypass the wait.

v 2.19

enabled the debug spam and sometimes got message "Player must wait more" instead of a tp and sometimes... not even that, it would state the location it had found which was ok to tp to... then do nothing.

**Comment by RoboMWM** [comment]
2.19?

That's not what I hear in #77

**Comment by RoboMWM** [comment]
Duplicate of #77
