### ISSUE TITLE
Abnormally high tick consumption

### ISSUE THREAD

**Issue by ItsSynchro** [AcmeProject/WildernessTp#79]
Hello, whilst using the latest version I'm getting abnormally high tick consumption. https://timings.aikar.co/?id=c636a792da3945d29db94c9fac83ef7c#plugins

### **Server Version**
git-Tuinity-"32ac48d" (MC: 1.15.2)

### **Plugin Version**
v2.19-2db6004

**Comment by RoboMWM** [comment]
Not seeing any issues here. Seems the server is running fine.
