### ISSUE TITLE
No Suitable Locations Found

### ISSUE THREAD

**Issue by KingSwag2002** [AcmeProject/WildernessTp#88]
Defaults can use the sign, it always says can find suitable location, but the owner can use it just fine and im not sure how to fix this i even tried removing blocked biomes

**Comment by RoboMWM** [comment]
and your /version and /version wild?

**Comment by RoboMWM** [comment]
and your config?

**Comment by Gracv** [comment]
I have the same issue in the nether.
/version wild - 2.21-39eeaba
/version - Purpur 1.16.4, Build 820

**Comment by RoboMWM** [comment]
purpur hmm. I know billy has done nether-related stuff before but idk if it's in his server mod. Any difference when using a Paper-generated nether and server?

**Comment by RoboMWM** [comment]
also, I did hear the nether was changed, maybe it's likely we need more retries?

**Comment by Gracv** [comment]
Okay, I know why I have this problem. I'm using datapack for doubling nether height. With normal nether height plugin is working, but with datapack not. I don't know if I can paste link to download this datapack but I downloaded that from purpur discord.

**Comment by RoboMWM** [comment]
Thank you, that's very helpful information! Links are ok

So, the thing is that this plugin checks for the "vanilla" nether by seeing if there's bedrock at y=128. Since you have the doubled nether height, the ceiling is now at y=256, so it's using the regular check (highest block); none are suitable since the highest block is all bedrock.

This check was made this way to account for nether generators that don't put in a ceiling - I use one that doesn't do a ceiling. Since this appears to be a more common case (double nether height) I suppose I'll put in an additional check at y=256.

**Comment by Gracv** [comment]
Issue is not fixed in newest build (2.23-04e8af7) I build plugin myself.

**Comment by RoboMWM** [comment]
Does he not do a bedrock ceiling...???

**Comment by Gracv** [comment]
> Does he not do a bedrock ceiling...???
I don't understand. Error is the same, "No suitable locations found"

**Comment by RoboMWM** [comment]
What block is at y=255?

**Comment by Gracv** [comment]
> What block is at y=255?

Bedrock

**Comment by RoboMWM** [comment]
It should be detecting it as vanilla nether then and using the appropriate algorithm... However, I think that algorithm only goes to y=126 so maybe I will need to do something different altogether, ugh.

**Comment by RoboMWM** [comment]
hmm, can you also see if there are many open spaces at y=126?

**Comment by Gracv** [comment]
> hmm, can you also see if there are many open spaces at y=126?

![image](https://user-images.githubusercontent.com/37741582/100248415-bb7c6600-2f3b-11eb-9808-165bffda660a.png)

Yep, I'm standing on Y:126 in this screenshot

**Comment by RoboMWM** [comment]
Ok I dun goof'd, thought I modified the right class and instead did the wrong one lol. Either way I still need to do what I said what I need to do, which is check past y=126 for a safe location as well anyways.

**Comment by RoboMWM** [comment]
Ok, should be fixed in the upcoming 2.25 release. Let me know if that fixes it or not. (Or you can build as you have last time.)

**Comment by Gracv** [comment]
Yes, it's working now. Thanks for the fix
