### ISSUE TITLE
Portal Active In Wrong World

### ISSUE THREAD

**Issue by himino666** [AcmeProject/WildernessTp#89]
Portals created in a specific world can be used in other worlds if you go to the specific coords of the created portal. In Portals.yml the worldname is saved, but does not do anything with it. My players have reported that they randomly get teleported when they are in The End and in The Nether, because they somehow walked past the same coordinates as that was created in World.

**Comment by RoboMWM** [comment]
watch bukkitdev for 2.24 and lemme know if that fixes it.
