### ISSUE TITLE
Named portals does not randomly teleport players to the world with the same name

### ISSUE THREAD

**Issue by Kaesor** [AcmeProject/WildernessTp#90]
Server : Paper-MC #259
Plugins version : Wilderness-Tp 2.25 // Multiverse-Core-4.2.2 (test in : 4.1.0 and 4.2.2)

/wildtp create [world's name] > it teleport on same world where was create portal (whatever the world indicated)

World's tried : Resource, world
Portal world's name : Build

**Comment by RoboMWM** [comment]
Yup, he made a PR where he added an, IMO, very useless feature of "linking" portals. In a random tp plugin. I'll try to get a fix in...

**Comment by RoboMWM** [comment]
ok, think I found an easy fix.
