### ISSUE TITLE
If enabled Wait time in the WildernessTp teleport out from Hide And Seek minigame

### ISSUE THREAD

**Issue by andris155** [AcmeProject/WildernessTp#95]
https://www.youtube.com/watch?v=TyfohN1wxXg
Couldn't cancel waiting if the player teleports away?

1. I use wild teleport command.
2. The wild plugin don't teleport instantly, because I enabled Wait time.
3. When I waited to teleport the wild. I used the minigame join command.
4. I joined to the minigame.
5. The wild wait time ended, when I'm already on the mini-game.
6. The WildernessTp teleported to the wild from the minigame.

**Comment by RoboMWM** [comment]
Pretty sure any plugin with a warmup has this issue, but teleporting beforehand should cause a playermoveevent to fire after the teleport. Is the minigame in the same world?

**Comment by andris155** [comment]
The minigame is same world in test server. But on my server the minigame is in another world.

**Comment by RoboMWM** [comment]
wait so the issue doesn't happen on the test server?

(No I haven't watched the video yet and I read much faster than I watch)

**Comment by andris155** [comment]
But it does happen, only there is the minigame set in the same world.

**Comment by RoboMWM** [comment]
Weird. I guess I'll try to see if there's a good way to cancel on teleport, only issue is identifying that the teleport event indeed was not caused by wilderness-tp (so it doesn't cancel itself). Hmm.

**Comment by RoboMWM** [comment]
@andris155 why'd you close this?
