### ISSUE TITLE
NPE on griefdefender/text api sendMessage

### ISSUE THREAD

**Issue by hkkongou** [AcmeProject/WildernessTp#96]
hi, when i use /rtp to a new location, these error? message pop up.
These error does not 100% pop up all the time, sometimes /rtp will happen
![image](https://user-images.githubusercontent.com/61608872/112756941-02798580-901a-11eb-9953-9c47a28ccab3.png)
![image](https://user-images.githubusercontent.com/61608872/112756997-4076a980-901a-11eb-958d-6eeccdcc924d.png)

server log:
https://paste.gg/p/anonymous/d8e174a41cc34bbfb6c05e8ffcdad2f9

*btw i have a question, do wild tp hook with griefdefender claims?

**Comment by RoboMWM** [comment]
I highly recommend using GriefPrevention, but yes WildernessTP will work with any region plugin.

Hmm... I wonder how griefdefender is sending a message. Idk if it's paper's "adventure" text API or griefdefender's way of passing in stuff to be sent that's causing issues here... 

Ok just looked up his code and it looks like he uses the adventure API directly in his plugin. Interesting. So that API is not liking the fact that the player permissions it's trying to check is not real. I'll have to take a look at whatever the adventure text API is doing...

**Comment by hkkongou** [comment]
does that mean these error are wildness tp side problem?
if so, are you going to fix it?

**Comment by RoboMWM** [comment]
Not necessarily a wildtp problem but can be caused by something it does sure. It's just figuring out what causes it is a little more annoying since it's not straightforward here... I haven't had time to poke inside of the text API at the moment, but I've heard it has caused issues with other plugins ever since they tried sticking that API straight into Paper.

**Comment by hkkongou** [comment]
> Not necessarily a wildtp problem but can be caused by something it does sure. It's just figuring out what causes it is a little more annoying since it's not straightforward here... I haven't had time to poke inside of the text API at the moment, but I've heard it has caused issues with other plugins ever since they tried sticking that API straight into Paper.

will there be any update soon?

**Comment by RoboMWM** [comment]
had this amongst other issues bookmarked, sorry haven't looked into it yet. As per the stacktrace it has something to do with SpigotAdapter class line 121 in kyori's text api.

**Comment by RoboMWM** [comment]
I have no idea what version he's using because I can't find that class in their repo nor in the few branches I checked.

**Comment by RoboMWM** [comment]
huh, seems his plugin isn't even fully open source as I cannot find his gradle.build file...

**Comment by hkkongou** [comment]
Should I find Griefdefender staff to look into this ?🤔

**Comment by RoboMWM** [comment]
ok I found something, he has some weird structure.

**Comment by RoboMWM** [comment]
Ok I'm looking at the text API and I see no adapter package or any classes named as such, so I'm not really sure how that API is shaded in or what

**Comment by RoboMWM** [comment]
Finally found it... was part of a different repo named "text-extras"...

**Comment by hkkongou** [comment]
excuse me, have you fixed the problem ? i saw there is a new build uploaded on 12 of april, does that contain this fix or not?

**Comment by RoboMWM** [comment]
Been busy with other priorities. This isn't game breaking (it just causes some log spam) and the fix isn't easy so it's a bit lower on my list of priorities. If you want me to prioritize it you can become a [patron on Patreon](https://r.robomwm.com/patreon) but until then it's more of a "when I get to it" sort of deal.

Anyways, you can try the latest dev build and see if that works: https://ci.appveyor.com/project/RoboMWM39862/wildernesstp/builds/38852928/artifacts

**Comment by RoboMWM** [comment]
Yea, I did try something in the latest dev build, did it work?

**Comment by hkkongou** [comment]
Excuse me, where can I download the latest dev build?

**Comment by RoboMWM** [comment]
the link is in my prior comment

**Comment by RoboMWM** [comment]
"Saving oversized chunk" has nothing to do with the error you're seeing btw. That's a different issue.

**Comment by hkkongou** [comment]
still exist
![image](https://user-images.githubusercontent.com/61608872/117964128-d4df6600-b353-11eb-9958-25cc1ea22231.png)

![image](https://user-images.githubusercontent.com/61608872/117964161-dc9f0a80-b353-11eb-8f45-4849216ad9c9.png)

**Comment by RoboMWM** [comment]
Ok thank you. I figured that was what would happened but didn't know for sure.

The easy solution for now will cause a "permission denied" message to appear from griefdefender but there's no other way that I know of to deal with this for now. I'll implement that mitigation soon. The other option is to use a different plugin like GriefPrevention.
