### ISSUE TITLE
Sounds are not working.

### ISSUE THREAD

**Issue by KoxSosen** [AcmeProject/WildernessTp#99]
The sound feature of the plugin is not working. I'm using the latest build, with a working and valid sound effect on 1.16.5.

**Comment by RoboMWM** [comment]
the sound will silently fail if it's invalid since I recall having reports of people wanting to be able to disable the sound or etc. I guess I could have it print something to console or something.

**Comment by KoxSosen** [comment]
Yes, please try to add a debug catch to it, so I can see if the issue is with my client or not.
